=== alexandrapaziy/solvd/src/main/resources/xsd/account.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="BankType">
        <xs:sequence>
            <xs:element name="bankId" type="xs:long" minOccurs="1"/>
            <xs:element name="bankName" type="xs:string"/>
            <xs:element name="bankLocation" type="xs:string"/>
            <xs:element name="bankPhone" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="BankBranchType">
        <xs:sequence>
            <xs:element name="bankBranchId" type="xs:int" minOccurs="0"/>
            <xs:element name="bank" type="BankType"/>
            <xs:element name="bankBranchLocation" type="xs:string"/>
            <xs:element name="bankBranchPhone" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="CustomerType">
        <xs:sequence>
            <xs:element name="customerId" type="xs:long" minOccurs="1"/>
            <xs:element name="customerName" type="xs:string"/>
            <xs:element name="customerSurname" type="xs:string"/>
            <xs:element name="customerPatronymic" type="xs:string"/>
            <xs:element name="customerPhone" type="xs:string"/>
            <xs:element name="customerEmail" type="xs:string"/>
            <xs:element name="customerAddress" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="AccountTypeType">
        <xs:sequence>
            <xs:element name="accountTypeId" type="xs:int"/>
            <xs:element name="accountTypeName" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="AccountType">
        <xs:sequence>
            <xs:element name="accountId" type="xs:long" minOccurs="1"/>
            <xs:element name="customer" type="CustomerType"/>
            <xs:element name="accountType" type="AccountTypeType"/>
            <xs:element name="bankBranch" type="BankBranchType"/>
            <xs:element name="balance" type="xs:double" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="account" type="AccountType"/>

</xs:schema>

=== alexandrapaziy/solvd/src/main/resources/xml/account.xml
<?xml version="1.0" encoding="UTF-8" ?>

<account xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../xsd/account.xsd">
    <accountId>1</accountId>
    <customer>
        <customerId>1</customerId>
        <customerName>Mykola</customerName>
        <customerSurname>Bilak</customerSurname>
        <customerPatronymic>Oleksandrovich</customerPatronymic>
        <customerPhone>+380675462847</customerPhone>
        <customerEmail>mykolabilak@gmail.com</customerEmail>
        <customerAddress>Kyiv, Street Ivan Franko, 12</customerAddress>
    </customer>
    <accountType>
        <accountTypeId>1</accountTypeId>
        <accountTypeName>current</accountTypeName>
    </accountType>
    <bankBranch>
        <bankBranchId>1</bankBranchId>
        <bank>
            <bankId>1</bankId>
            <bankName>MonoBank</bankName>
            <bankLocation>Kyiv, Avtozavodska St, 54/19</bankLocation>
            <bankPhone>+380936178150</bankPhone>
        </bank>
        <bankBranchLocation>Kyiv, Avtozavodska St, 54/19</bankBranchLocation>
        <bankBranchPhone>+380936178150</bankBranchPhone>
    </bankBranch>
    <balance>1000</balance>
</account>
