=== alexandrapaziy/solvd/src/main/resources/xsd/bankBranch.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="BankType">
        <xs:sequence>
            <xs:element name="bankId" type="xs:long" minOccurs="1"/>
            <xs:element name="bankName" type="xs:string"/>
            <xs:element name="bankLocation" type="xs:string"/>
            <xs:element name="bankPhone" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="BankBranchType">
        <xs:sequence>
            <xs:element name="bankBranchId" type="xs:int" minOccurs="0"/>
            <xs:element name="bank" type="BankType"/>
            <xs:element name="bankBranchLocation" type="xs:string"/>
            <xs:element name="bankBranchPhone" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="bankBranch" type="BankBranchType"/>

</xs:schema>

=== alexandrapaziy/solvd/src/main/resources/xml/bankBranch.xml
<?xml version="1.0" encoding="UTF-8" ?>

<bankBranch xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="../xsd/bankBranch.xsd">
    <bankBranchId>1</bankBranchId>
    <bank>
        <bankId>1</bankId>
        <bankName>MonoBank</bankName>
        <bankLocation>Kyiv, Avtozavodska St, 54/19</bankLocation>
        <bankPhone>+380936178150</bankPhone>
    </bank>
    <bankBranchLocation>Kyiv, Avtozavodska St, 54/19</bankBranchLocation>
    <bankBranchPhone>+380936178150</bankBranchPhone>
</bankBranch>
