=== alexandrapaziy/solvd/src/main/resources/xsd/customer.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="CustomerType">
        <xs:sequence>
            <xs:element name="customerId" type="xs:long" minOccurs="1"/>
            <xs:element name="customerName" type="xs:string"/>
            <xs:element name="customerSurname" type="xs:string"/>
            <xs:element name="customerPatronymic" type="xs:string"/>
            <xs:element name="customerPhone" type="xs:string"/>
            <xs:element name="customerEmail" type="xs:string"/>
            <xs:element name="customerAddress" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="customer" type="CustomerType"/>

</xs:schema>

=== alexandrapaziy/solvd/src/main/resources/xml/customer.xml
<?xml version="1.0" encoding="UTF-8" ?>

<customer xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="../xsd/customer.xsd">
    <customerId>1</customerId>
    <customerName>Mykola</customerName>
    <customerSurname>Bilak</customerSurname>
    <customerPatronymic>Oleksandrovich</customerPatronymic>
    <customerPhone>+380675462847</customerPhone>
    <customerEmail>mykolabilak@gmail.com</customerEmail>
    <customerAddress>Kyiv, Street Ivan Franko, 12</customerAddress>
</customer>
